[package]
name = "atri-elo-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1"
dashmap = { version = "4", features = ["rayon"] }
itertools = "0.10"
tracing = "0.1"
